name: Security&Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: security-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/secret-scanning.yml@main
    secrets: inherit
